name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1

    - name: pack
      run: dotnet pack -c Release -o ./out

    - uses: actions/upload-artifact@v1
      with:
        name: vsmodtemplate
        path: ./out
